[package]
name = "stark_overflow"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.10.1"
openzeppelin = "0.20.0"

[dev-dependencies]
snforge_std = "0.37.0"
assert_macros = "2.10.1"

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"